# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------


from .. import try_manual


# EXAMPLE: /GalleryImages/get/Get a gallery.
@try_manual
def step_group_list(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sig group-list '
             '--location "myLocation"',
             checks=checks)


# EXAMPLE: /GalleryImages/patch/Update a simple gallery image.
@try_manual
def step_update(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sig update '
             '--hyper-v-generation "V1" '
             '--identifier offer="myOfferName" publisher="myPublisherName" sku="mySkuName" '
             '--os-state "Generalized" '
             '--os-type "Windows" '
             '--name "{myGalleryImage}" '
             '--gallery-name "myGalleryName" '
             '--resource-group "{rg}"',
             checks=checks)


# EXAMPLE: /GalleryImages/post/Add sharing id to the sharing profile of a gallery.
@try_manual
def step_share(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sig share '
             '--gallery-name "myGalleryName" '
             '--resource-group "{rg}" '
             '--groups type="Subscriptions" ids="34a4ab42-0d72-47d9-bd1a-aed207386dac" ids="380fd389-260b-41aa-bad9-0a8'
             '3108c370b" '
             '--groups type="AADTenants" ids="c24c76aa-8897-4027-9b03-8f7928b54ff6" '
             '--operation-type "Add"',
             checks=checks)


# EXAMPLE: /GalleryImages/post/reset sharing profile of a gallery.
@try_manual
def step_share2(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sig share '
             '--gallery-name "myGalleryName" '
             '--resource-group "{rg}" '
             '--operation-type "Reset"',
             checks=checks)


# EXAMPLE: /SharedGalleryImages/get/Get a gallery.
@try_manual
def step_image_definition_list(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sig image-definition list '
             '--gallery-unique-name "galleryUniqueName" '
             '--location "myLocation"',
             checks=checks)


# EXAMPLE: /SharedGalleryImageVersions/get/Get a gallery.
@try_manual
def step_image_version_list(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sig image-version list '
             '--gallery-image-name "{myGalleryImage}" '
             '--gallery-unique-name "galleryUniqueName" '
             '--location "myLocation"',
             checks=checks)


# EXAMPLE: /SshPublicKeys/put/Create a new SSH public key resource.
@try_manual
def step_create(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sshkey create '
             '--location "westus" '
             '--public-key "{{ssh-rsa public key}}" '
             '--resource-group "{rg}" '
             '--name "{mySshPublicKey}"',
             checks=checks)


# EXAMPLE: /SshPublicKeys/get/Get an ssh public key.
@try_manual
def step_show(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az sshkey show '
             '--resource-group "{rg}" '
             '--name "{mySshPublicKey}"',
             checks=checks)

