# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

import os
from azure.cli.testsdk import ScenarioTest
from azure.cli.testsdk import ResourceGroupPreparer
from .example_steps import step_group_list
from .example_steps import step_update
from .example_steps import step_share
from .example_steps import step_share2
from .example_steps import step_image_definition_list
from .example_steps import step_image_version_list
from .example_steps import step_create
from .example_steps import step_show
from .. import (
    try_manual,
    raise_if,
    calc_coverage
)


TEST_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '..'))


# Env setup_scenario
@try_manual
def setup_scenario(test, rg):
    pass


# Env cleanup_scenario
@try_manual
def cleanup_scenario(test, rg):
    pass


# Testcase: Scenario
@try_manual
def call_scenario(test, rg):
    setup_scenario(test, rg)
    step_group_list(test, rg, checks=[])
    step_update(test, rg, checks=[
        test.check("hyperVGeneration", "V1", case_sensitive=False),
        test.check("identifier.offer", "myOfferName", case_sensitive=False),
        test.check("identifier.publisher", "myPublisherName", case_sensitive=False),
        test.check("identifier.sku", "mySkuName", case_sensitive=False),
        test.check("osState", "Generalized", case_sensitive=False),
        test.check("osType", "Windows", case_sensitive=False),
        test.check("name", "{myGalleryImage}", case_sensitive=False),
    ])
    step_share(test, rg, checks=[])
    step_share2(test, rg, checks=[])
    step_image_definition_list(test, rg, checks=[])
    step_image_definition_list(test, rg, checks=[])
    step_image_version_list(test, rg, checks=[])
    step_image_version_list(test, rg, checks=[])
    step_create(test, rg, checks=[
        test.check("location", "westus", case_sensitive=False),
        test.check("publicKey", "{{ssh-rsa public key}}", case_sensitive=False),
        test.check("name", "{mySshPublicKey}", case_sensitive=False),
    ])
    step_show(test, rg, checks=[
        test.check("location", "westus", case_sensitive=False),
        test.check("publicKey", "{{ssh-rsa public key}}", case_sensitive=False),
        test.check("name", "{mySshPublicKey}", case_sensitive=False),
    ])
    cleanup_scenario(test, rg)


# Test class for Scenario
@try_manual
class VmScenarioTest(ScenarioTest):

    def __init__(self, *args, **kwargs):
        super(VmScenarioTest, self).__init__(*args, **kwargs)
        self.kwargs.update({
            'mySshPublicKey': 'mySshPublicKeyName',
            'myGalleryImage': 'myGalleryImageName',
        })


    @ResourceGroupPreparer(name_prefix='clitestvm_myResourceGroup'[:7], key='rg', parameter_name='rg')
    def test_vm_Scenario(self, rg):
        call_scenario(self, rg)
        calc_coverage(__file__)
        raise_if()

